name: Linting and Unit Tests

on:
    workflow_dispatch:
    pull_request:
        branches: ["main", "dev"]

jobs:
    linting_and_unit_tests:
        runs-on: ubuntu-22.04
        timeout-minutes: 60

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                submodules: "recursive"

            - name: Install pnpm
              uses: pnpm/action-setup@v5
              with:
                version: 10

            - name: Use Node LTS
              uses: actions/setup-node@v6
              with:
                node-version: 24.x
                cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Run Linting
              run: pnpm run check:ci

            - name: Run unit tests
              run: pnpm run tests
