name: Linting and Unit Tests

on:
    workflow_dispatch:
    pull_request:
        branches: ["main", "dev"]

permissions:
    contents: read

jobs:
    linting_and_unit_tests:
        if: github.repository == 'amaify/chainwright'
        runs-on: ubuntu-22.04
        timeout-minutes: 60
        strategy:
              matrix:
                node-version: [24]
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                submodules: "recursive"

            - name: Install pnpm
              uses: pnpm/setup@v2
              with:
                runtime: node@${{ matrix.node-version }}
                version: 11
                install: false
                cache: true

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Run Linting
              run: pnpm run check:ci

            - name: Run unit tests
              run: pnpm run tests
